pde_type: Klein-Gordon
boundary_condition: neumann
num_trajectories: 5328
num_snapshots: 100
nt: 15000
domain:
  Lx:
  - -3.0
  - 3.0
  Ly:
  - -3.0
  - 3.0
  T:
  - 0.0
  - 20.0
grid:
  nx: 300
  ny: 300
m_classes:
- constant
- defects
- gradient
- multiscale
- phase
- piecewise
- quasiperiodic
- topological
c_classes:
- constant
- layered
- periodic_structure
- piecewise_constant
- quasiperiodic
- turbulent
- waveguide
